# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170704_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='id',
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
